import { describe, it, expect, vi } from "vitest";
import { renderMarkdown } from "@/lib/report/markdown";
import { makeFinding, makeRenderData } from "./report-fixtures";

vi.mock("server-only", () => ({}));

describe("renderMarkdown", () => {
  it("is een Engels rapport met meta, scores, categorie-tabel en findings", () => {
    const md = renderMarkdown(
      makeRenderData({
        findings: [
          makeFinding({
            id: "https:missing",
            title: "HTTPS ontbreekt",
            severity: "critical",
            category: "http",
            description: "Geen TLS",
            remediation: "Regel een certificaat",
            evidence: "curl -I example.com",
          }),
        ],
      }),
    );

    expect(md).toContain("# ScanPal Report");
    expect(md).toContain("Example Site");
    expect(md).toContain("https://example.com");
    expect(md).toContain("**Overall score:** 80/100");
    expect(md).toContain("| HTTP & Security | 100 |");
    expect(md).toContain("| AEO & Browser | not scanned |");
    expect(md).toContain("| Critical | 0 |");
    expect(md).toContain("### Critical");
    expect(md).toContain("#### HTTPS ontbreekt");
    expect(md).toContain("**Description:**");
    expect(md).toContain("Geen TLS");
    expect(md).toContain("**Remediation:**");
    expect(md).toContain("Regel een certificaat");
    expect(md).toContain("**Evidence:**");
    expect(md).toContain("curl -I example.com");
    expect(md).toContain("Generated by ScanPal");
  });

  it("toont '… and N more' voor afgekapte findings per ernst", () => {
    const md = renderMarkdown(
      makeRenderData(
        {
          findings: [
            makeFinding({ id: "h:1", title: "Hoog", severity: "high" }),
          ],
        },
        { critical: 0, high: 5, medium: 0, low: 0, info: 0 },
      ),
    );
    expect(md).toContain("… and 5 more");
  });

  it("rendert gestructureerd evidence via evidenceText (request/response + bundle-secrets)", () => {
    const md = renderMarkdown(
      makeRenderData({
        findings: [
          makeFinding({
            id: "xss:probe",
            title: "Reflected XSS",
            severity: "high",
            evidence: {
              request: "GET /?q=<script>alert(1)</script>",
              response: "200 OK",
            },
          }),
          makeFinding({
            id: "secrets:bundles",
            title: "Secrets in bundles",
            severity: "critical",
            evidence: {
              kind: "bundle-secrets",
              matches: [
                {
                  key_type: "stripe_secret_key",
                  provider: "stripe",
                  file: "https://example.com/app.js",
                  sourcemap: false,
                  match_preview: "sk_l…ive",
                  severity: "critical",
                },
              ],
              notes: [],
            },
          }),
        ],
      }),
    );
    expect(md).toContain("GET /?q=");
    expect(md).toContain("200 OK");
    expect(md).toContain(
      "stripe_secret_key stripe https://example.com/app.js sk_l…ive",
    );
  });

  it("toont 'No findings in this scan.' bij een lege scan", () => {
    const md = renderMarkdown(makeRenderData({ findings: [] }));
    expect(md).toContain("No findings in this scan.");
  });

  it("toont een Fix Prompts-sectie wanneer prompts zijn meegegeven (plan 60)", () => {
    const md = renderMarkdown(
      makeRenderData(
        {
          findings: [
            makeFinding({
              id: "https:missing",
              title: "HTTPS ontbreekt",
              severity: "high",
            }),
          ],
        },
        undefined,
        ["# Fix prompt — Example Site\n\nFix the HTTPS issue."],
      ),
    );
    expect(md).toContain("## Fix Prompts");
    expect(md).toContain("### Fix prompt 1");
    expect(md).toContain("Fix the HTTPS issue.");
  });
});