import "server-only";

import { evidenceText, scanCategories, severityOrder } from "@scanpal/shared";
import {
  categoryLabelEn,
  severityLabel,
  statusLabelEn,
  triggerLabelEn,
  type ReportRenderData,
} from "./data";

function displayUrl(url: string): string {
  return /^https?:\/\//i.test(url) ? url : `https://${url}`;
}

function dateTime(iso: string): string {
  return new Date(iso).toISOString().replace("T", " ").replace(/\.\d+Z$/, " UTC");
}

function esc(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

/**
 * Kiest een code-fence die langer is dan elke backtick-run in de inhoud, zodat
 * ```-fences in evidence/fix-prompts het markdown-rapport niet corrumperen
 * (vanaf de eerste finding met backticks).
 */
function fenceFor(text: string): string {
  const runs = text.match(/`+/g)?.map((m) => m.length) ?? [];
  const max = runs.length > 0 ? Math.max(...runs) : 0;
  return "`".repeat(Math.max(3, max + 1));
}

/**
 * Markdown-renderer (Engels, besluit 13): koppen, meta-tabel, overall score,
 * per-categorie-tabel, summary en findings per ernst met description,
 * remediatie + evidence (via `evidenceText`), "… and N more" en een footer.
 */
export function renderMarkdown(input: ReportRenderData): string {
  const { data, omitted } = input;
  const branding = { hide_branding: false, ...input.branding };
  const { scan, site, score, category_scores, summary, findings } = data;
  const siteName = site.label ?? site.url;

  const lines: string[] = [];
  const title = branding.report_name ?? (branding.hide_branding ? "Report" : "ScanPal Report");
  lines.push(`# ${title}`, "");
  if (branding.logo_url) lines.push(`![Logo](${branding.logo_url})`, "");
  if (branding.primary_color) lines.push(`**Brand color:** ${branding.primary_color}`, "");
  lines.push(`**Site:** ${siteName}`, "");
  lines.push(`**URL:** ${displayUrl(site.url)}`, "");
  lines.push(`**Scan ID:** ${scan.id}`, "");
  lines.push(`**Trigger:** ${triggerLabelEn[scan.trigger]}`, "");
  lines.push(`**Created:** ${dateTime(scan.created_at)}`, "");
  lines.push(`**Completed:** ${dateTime(scan.completed_at)}`, "");
  lines.push(`**Overall score:** ${score}/100`, "");

  lines.push("## Category Scores", "", "| Category | Score |", "|---|---|");
  for (const category of scanCategories) {
    const value = category_scores[category];
    lines.push(
      `| ${categoryLabelEn[category]} | ${value === null ? "not scanned" : value} |`,
    );
  }

  if (category_scores.compliance !== null) {
    lines.push(
      "",
      "> Compliance findings are automated observations based on the publicly accessible",
      "> HTML/scripts of the site. They are not legal advice and not a complete obligations",
      "> check (e.g. GDPR/CCPA).",
      "",
    );
  }

  lines.push("", "## Summary", "", "| Severity | Count |", "|---|---|");
  for (const severity of severityOrder) {
    lines.push(`| ${severityLabel[severity]} | ${summary[severity]} |`);
  }

  lines.push("", "## Findings");

  let anyFinding = false;
  for (const severity of severityOrder) {
    const bucket = findings.filter((finding) => finding.severity === severity);
    const extra = omitted[severity];
    if (bucket.length === 0 && extra === 0) continue;
    anyFinding = true;

    lines.push("", `### ${severityLabel[severity]}`, "");
    for (const finding of bucket) {
      lines.push(`#### ${finding.title}`, "");
      lines.push(`- **Category:** ${categoryLabelEn[finding.category]}`);
      lines.push(`- **Severity:** ${severityLabel[finding.severity]}`);
      lines.push(`- **Status:** ${statusLabelEn[finding.status]}`);
      if (finding.note) lines.push(`- **Note:** ${esc(finding.note)}`);
      lines.push("", "**Description:**", "", finding.description, "");
      lines.push("", "**Remediation:**", "", finding.remediation, "");
      const evidence = evidenceText(finding.evidence);
      if (evidence) {
        const fence = fenceFor(evidence);
        lines.push("", "**Evidence:**", "", fence, evidence, fence, "");
      }
    }
    if (extra > 0) {
      lines.push("", `… and ${extra} more`, "");
    }
  }

  if (!anyFinding) {
    lines.push("", "No findings in this scan.", "");
  }

  if (input.prompts && input.prompts.length > 0) {
    lines.push("", "## Fix Prompts");
    lines.push(
      "",
      "Copy-paste prompts for an AI editor (Cursor/Claude/Windsurf) to fix the findings above.",
      "",
    );
    input.prompts.forEach((prompt, index) => {
      const fence = fenceFor(prompt);
      lines.push("", `### Fix prompt ${index + 1}`, "", fence, prompt, fence, "");
    });
  }

  if (!branding.hide_branding) {
    lines.push("", "---", "", `_Generated by ScanPal on ${new Date().toISOString().slice(0, 10)}._`);
  }
  return lines.join("\n");
}
