import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { pool } from "@/lib/db";
import { getPublicReport } from "@/lib/public-report-core";
import { severityLabel, categoryLabelEn } from "@/lib/report/data";

export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const report = await getPublicReport(pool, (await params).token);
  const title = report?.branding.report_name ?? (report?.branding.hide_branding ? "Report" : "ScanPal Report");
  return { title, robots: { index: false, follow: false } };
}

export default async function PublicReportPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const report = await getPublicReport(pool, (await params).token);
  if (!report) notFound();
  const { data, branding } = report;
  const title = branding.report_name ?? (branding.hide_branding ? "Report" : "ScanPal Report");
  return (
    <main className="flex-1 px-4 py-10">
      <article className="mx-auto w-full max-w-4xl space-y-8">
        <header className="border-b border-slate-800 pb-6">
          {branding.logo_url && <img src={branding.logo_url} alt="Logo" className="mb-5 h-10 max-w-48 object-contain object-left" />}
          <h1 className="text-3xl font-bold" style={{ color: branding.primary_color ?? undefined }}>{title}</h1>
          <p className="mt-2 text-slate-400">{data.site.label ?? data.site.url} · {data.score}/100</p>
        </header>
        <section className="grid gap-4 sm:grid-cols-2">
          {Object.entries(data.summary).map(([severity, count]) => (
            <div key={severity} className="rounded-xl border border-slate-800 bg-slate-900/50 p-4">
              <p className="text-xs uppercase tracking-wide text-slate-500">{severityLabel[severity as keyof typeof severityLabel]}</p>
              <p className="mt-1 text-2xl font-bold">{count}</p>
            </div>
          ))}
        </section>
        <section>
          <h2 className="text-xl font-semibold">Findings</h2>
          {data.findings.length === 0 ? (
            <p className="mt-4 text-sm text-slate-500">No findings in this scan.</p>
          ) : (
            <div className="mt-4 space-y-3">
              {data.findings.map((finding) => (
                <article key={finding.id} className="rounded-xl border border-slate-800 bg-slate-900/50 p-5">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <h3 className="font-semibold">{finding.title}</h3>
                    <span className="text-xs text-slate-400">{severityLabel[finding.severity]} · {categoryLabelEn[finding.category]}</span>
                  </div>
                  <p className="mt-3 text-sm text-slate-300">{finding.description}</p>
                  <p className="mt-3 text-sm text-slate-400">{finding.remediation}</p>
                </article>
              ))}
            </div>
          )}
        </section>
        {!branding.hide_branding && <footer className="border-t border-slate-800 pt-6 text-center text-xs text-slate-600">Generated by ScanPal.</footer>}
      </article>
    </main>
  );
}
